name: first

on: 
  push:

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
      # checkout action will clone git repo into local system
        uses: actions/checkout@v2
      - name: Step two
        run: |
          echo "Code is now accessible."
          echo "This is my first job"
         

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: |
          echo "Code is now accessible."
          dir
